# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CloneDanggeunMarket' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CloneDanggeunMarket
pod 'Alamofire'
pod 'Kingfisher'

  target 'CloneDanggeunMarketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CloneDanggeunMarketUITests' do
    # Pods for testing
  end

end
